# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
        dotnet publish FileFormatDetector.Console -p:PublishProfile=FolderProfile
        dotnet publish ElfFormat -p:PublishProfile=FolderProfile
        dotnet publish PEFormat -p:PublishProfile=FolderProfile
        dotnet publish MachOFormat -p:PublishProfile=FolderProfile
        dotnet publish TextFilesFormat -p:PublishProfile=FolderProfile
        dotnet publish XmlFormat -p:PublishProfile=FolderProfile
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: FileFormatDetector.Console/bin/publish/*
        
